name: h-next
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - cudatoolkit=10.2
  - pip=22.0.*
  - rich
  - pip:
    - torch==1.13.1
    - torchvision==0.14.1
    - torchaudio==0.13.1
    - torch-summary==1.4.5
    - lovely-tensors
    - torchmetrics==0.10.3
    - pytorch-lightning==1.9.0
    - dataset
    - datasets
    - numpy
    - click
    - loguru
    - gitpython
    - wandb==0.13.9
    - matplotlib
    - oct2py
    - pytest
    - auto-tqdm
    - seaborn
    - scipy
    - scikit-learn
    - umap-learn
    - opencv-python
    - plotly
    - captum
    - distinctipy
    - einops
    - easydict
    - notebook
    - tensorboard==2.10.0
